// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$24 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$24() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(UTextAccess.class, "apply", constants$23.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$23.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(UTextExtract.class, "apply", constants$21.const$5);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$21.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(UTextReplace.class, "apply", constants$21.const$5);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(UTextCopy.class, "apply", constants$22.const$3);
}


