// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$43 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$43() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_BYTE,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "uregex_useTransparentBounds_70",
        constants$43.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "uregex_hasAnchoringBounds_70",
        constants$18.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "uregex_useAnchoringBounds_70",
        constants$43.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "uregex_hitEnd_70",
        constants$18.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "uregex_requireEnd_70",
        constants$18.const$5
    );
}


