// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$9 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$9() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "u_isJavaSpaceChar_73",
        constants$5.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "u_isWhitespace_73",
        constants$5.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "u_iscntrl_73",
        constants$5.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "u_isISOControl_73",
        constants$5.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "u_isprint_73",
        constants$5.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "u_isbase_73",
        constants$5.const$0
    );
}


