// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$50 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$50() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(uregex_getMatchCallback_73$callback.class, "apply", constants$21.const$2);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "uregex_getMatchCallback_73",
        constants$47.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_BYTE,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(URegexFindProgressCallback.class, "apply", constants$50.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$50.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(uregex_setFindProgressCallback_73$callback.class, "apply", constants$50.const$2);
}


