// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$51 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$51() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "uregex_setFindProgressCallback_73",
        constants$47.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(uregex_getFindProgressCallback_73$callback.class, "apply", constants$50.const$2);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "uregex_getFindProgressCallback_73",
        constants$47.const$2
    );
    static final MemorySegment const$3 = MemorySegment.ofAddress(0L);
    static final MemorySegment const$4 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("");
    static final MemorySegment const$5 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String(" Copyright (C) 2016 and later: Unicode, Inc. and others. License & terms of use: http://www.unicode.org/copyright.html ");
}


