// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ucpmap_get_70",
        constants$3.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(UCPMapValueFilter.class, "apply", constants$3.const$0);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$3.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(ucpmap_getRange_70$filter.class, "apply", constants$3.const$0);
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "ucpmap_getRange_70",
        constants$3.const$5
    );
}


