// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$48 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$48() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_BYTE,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(URegexFindProgressCallback.class, "apply", constants$48.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$48.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "uregex_setFindProgressCallback_70",
        constants$45.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "uregex_getFindProgressCallback_70",
        constants$45.const$2
    );
    static final MemorySegment const$5 = MemorySegment.ofAddress(0L);
}


