// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$26 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$26() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("tableSize"),
        JAVA_INT.withName("reserved1"),
        JAVA_INT.withName("reserved2"),
        JAVA_INT.withName("reserved3"),
        RuntimeHelper.POINTER.withName("clone"),
        RuntimeHelper.POINTER.withName("nativeLength"),
        RuntimeHelper.POINTER.withName("access"),
        RuntimeHelper.POINTER.withName("extract"),
        RuntimeHelper.POINTER.withName("replace"),
        RuntimeHelper.POINTER.withName("copy"),
        RuntimeHelper.POINTER.withName("mapOffsetToNative"),
        RuntimeHelper.POINTER.withName("mapNativeIndexToUTF16"),
        RuntimeHelper.POINTER.withName("close"),
        RuntimeHelper.POINTER.withName("spare1"),
        RuntimeHelper.POINTER.withName("spare2"),
        RuntimeHelper.POINTER.withName("spare3")
    ).withName("UTextFuncs");
    static final VarHandle const$1 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("tableSize"));
    static final VarHandle const$2 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("reserved1"));
    static final VarHandle const$3 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("reserved2"));
    static final VarHandle const$4 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("reserved3"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(UTextFuncs.clone.class, "apply", constants$23.const$0);
}


