// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "u_isxdigit_73",
        constants$5.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "u_ispunct_73",
        constants$5.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "u_isgraph_73",
        constants$5.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "u_isblank_73",
        constants$5.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "u_isdefined_73",
        constants$5.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "u_isspace_73",
        constants$5.const$0
    );
}


