// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "u_getIntPropertyMinValue_73",
        constants$6.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "u_getIntPropertyMaxValue_73",
        constants$6.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "u_getIntPropertyMap_73",
        constants$4.const$4
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_DOUBLE,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "u_getNumericValue_73",
        constants$6.const$4
    );
}


