// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_BYTE,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(UTextClone.class, "apply", constants$23.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$23.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(UTextNativeLength.class, "apply", constants$19.const$0);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$19.const$0
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_BYTE,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_BYTE
    );
}


