// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "utext_isWritable_73",
        constants$19.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "utext_hasMetaData_73",
        constants$19.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "utext_replace_73",
        constants$21.const$5
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_LONG,
        JAVA_BYTE,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "utext_copy_73",
        constants$22.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "utext_freeze_73",
        constants$1.const$0
    );
}


