// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$46 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$46() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "uregex_appendTailUText_70",
        constants$35.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "uregex_split_70",
        constants$46.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "uregex_splitUText_70",
        constants$38.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "uregex_setTimeLimit_70",
        constants$40.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "uregex_getTimeLimit_70",
        constants$35.const$3
    );
}


