// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final VarHandle const$0 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("clone"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(UTextFuncs.nativeLength.class, "apply", constants$19.const$0);
    static final VarHandle const$2 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("nativeLength"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(UTextFuncs.access.class, "apply", constants$23.const$5);
    static final VarHandle const$4 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("access"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(UTextFuncs.extract.class, "apply", constants$21.const$5);
}


