// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_LONG.withName("__clang_max_align_nonce1"),
        MemoryLayout.paddingLayout(8),
        MemoryLayout.paddingLayout(16).withName("__clang_max_align_nonce2")
    ).withName("max_align_t");
    static final VarHandle const$1 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("__clang_max_align_nonce1"));
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "u_versionFromString_70",
        constants$0.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "u_versionFromUString_70",
        constants$0.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "u_versionToString_70",
        constants$0.const$2
    );
}


