// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "u_charAge_70",
        constants$17.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "u_getUnicodeVersion_70",
        constants$1.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "u_getFC_NFKC_Closure_70",
        constants$12.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "utext_close_70",
        constants$17.const$4
    );
}


