// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$35 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$35() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "utext_setup_70",
        constants$35.const$0
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("line"),
        JAVA_INT.withName("offset"),
        MemoryLayout.sequenceLayout(16, JAVA_SHORT).withName("preContext"),
        MemoryLayout.sequenceLayout(16, JAVA_SHORT).withName("postContext")
    ).withName("UParseError");
    static final VarHandle const$3 = constants$35.const$2.varHandle(MemoryLayout.PathElement.groupElement("line"));
    static final VarHandle const$4 = constants$35.const$2.varHandle(MemoryLayout.PathElement.groupElement("offset"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "uregex_open_70",
        constants$35.const$5
    );
}


