// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$22.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(UTextMapOffsetToNative.class, "apply", constants$19.const$0);
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(UTextMapNativeIndexToUTF16.class, "apply", constants$19.const$4);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$19.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(UTextClose.class, "apply", constants$1.const$0);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$1.const$0
    );
}


