// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$38 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$38() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "uregex_setUText_70",
        constants$38.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "uregex_getText_70",
        constants$37.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "uregex_getUText_70",
        constants$37.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "uregex_refreshUText_70",
        constants$38.const$0
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_BYTE,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "uregex_matches_70",
        constants$38.const$5
    );
}


