// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$28 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$28() {}
    static final VarHandle const$0 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("extract"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(UTextFuncs.replace.class, "apply", constants$21.const$5);
    static final VarHandle const$2 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("replace"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(UTextFuncs.copy.class, "apply", constants$22.const$3);
    static final VarHandle const$4 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("copy"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(UTextFuncs.mapOffsetToNative.class, "apply", constants$19.const$0);
}


