// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$29 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$29() {}
    static final VarHandle const$0 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("mapOffsetToNative"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(UTextFuncs.mapNativeIndexToUTF16.class, "apply", constants$19.const$4);
    static final VarHandle const$2 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("mapNativeIndexToUTF16"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(UTextFuncs.close.class, "apply", constants$1.const$0);
    static final VarHandle const$4 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("close"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(UTextFuncs.spare1.class, "apply", constants$1.const$0);
}


