// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "u_forDigit_73",
        constants$16.const$5
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "u_charAge_73",
        constants$17.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "u_getUnicodeVersion_73",
        constants$1.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "u_getFC_NFKC_Closure_73",
        constants$12.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "utext_close_73",
        constants$17.const$5
    );
}


