// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "u_isIDStart_70",
        constants$5.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "u_isIDPart_70",
        constants$5.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "u_isIDIgnorable_70",
        constants$5.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "u_isJavaIDStart_70",
        constants$5.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "u_isJavaIDPart_70",
        constants$5.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "u_tolower_70",
        constants$6.const$0
    );
}


