// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$37 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$37() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_BYTE,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "uregex_matches64_70",
        constants$37.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "uregex_lookingAt_70",
        constants$36.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "uregex_lookingAt64_70",
        constants$37.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "uregex_find_70",
        constants$36.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "uregex_find64_70",
        constants$37.const$0
    );
}


