// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * signed char (*u_enumCharNames_73$fn)(void*,int,enum UCharNameChoice,char*,int);
 * }
 */
public interface u_enumCharNames_73$fn {

    byte apply(java.lang.foreign.MemorySegment context, int code, int nameChoice, java.lang.foreign.MemorySegment name, int length);
    static MemorySegment allocate(u_enumCharNames_73$fn fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$13.const$3, fi, constants$13.const$0, scope);
    }
    static u_enumCharNames_73$fn ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _context, int _code, int _nameChoice, java.lang.foreign.MemorySegment _name, int _length) -> {
            try {
                return (byte)constants$13.const$2.invokeExact(symbol, _context, _code, _nameChoice, _name, _length);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


