// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * signed char (*UCharEnumTypeRange)(void* context,int start,int limit,enum UCharCategory type);
 * }
 */
public interface UCharEnumTypeRange {

    byte apply(java.lang.foreign.MemorySegment context, int start, int limit, int type);
    static MemorySegment allocate(UCharEnumTypeRange fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$11.const$0, fi, constants$10.const$5, scope);
    }
    static UCharEnumTypeRange ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _context, int _start, int _limit, int _type) -> {
            try {
                return (byte)constants$11.const$1.invokeExact(symbol, _context, _start, _limit, _type);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


