// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * unsigned int (*ucpmap_getRange_73$filter)(void*,unsigned int);
 * }
 */
public interface ucpmap_getRange_73$filter {

    int apply(java.lang.foreign.MemorySegment context, int value);
    static MemorySegment allocate(ucpmap_getRange_73$filter fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$3.const$4, fi, constants$3.const$0, scope);
    }
    static ucpmap_getRange_73$filter ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _context, int _value) -> {
            try {
                return (int)constants$3.const$3.invokeExact(symbol, _context, _value);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


