// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * signed char (*URegexFindProgressCallback)(void* context,long matchIndex);
 * }
 */
public interface URegexFindProgressCallback {

    byte apply(java.lang.foreign.MemorySegment context, long matchIndex);
    static MemorySegment allocate(URegexFindProgressCallback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$48.const$1, fi, constants$48.const$0, scope);
    }
    static URegexFindProgressCallback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _context, long _matchIndex) -> {
            try {
                return (byte)constants$48.const$2.invokeExact(symbol, _context, _matchIndex);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


