// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * signed char (*URegexMatchCallback)(void* context,int steps);
 * }
 */
public interface URegexMatchCallback {

    byte apply(java.lang.foreign.MemorySegment context, int steps);
    static MemorySegment allocate(URegexMatchCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$49.const$2, fi, constants$21.const$2, scope);
    }
    static URegexMatchCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _context, int _steps) -> {
            try {
                return (byte)constants$49.const$3.invokeExact(symbol, _context, _steps);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


