// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * signed char (*uregex_getFindProgressCallback_70$callback)(void*,long);
 * }
 */
public interface uregex_getFindProgressCallback_70$callback {

    byte apply(java.lang.foreign.MemorySegment context, long matchIndex);
    static MemorySegment allocate(uregex_getFindProgressCallback_70$callback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$51.const$1, fi, constants$50.const$2, scope);
    }
    static uregex_getFindProgressCallback_70$callback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _context, long _matchIndex) -> {
            try {
                return (byte)constants$50.const$4.invokeExact(symbol, _context, _matchIndex);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


