// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * signed char (*URegexFindProgressCallback)(void* context,long matchIndex);
 * }
 */
public interface URegexFindProgressCallback {

    byte apply(java.lang.foreign.MemorySegment context, long matchIndex);
    static MemorySegment allocate(URegexFindProgressCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$50.const$3, fi, constants$50.const$2, scope);
    }
    static URegexFindProgressCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _context, long _matchIndex) -> {
            try {
                return (byte)constants$50.const$4.invokeExact(symbol, _context, _matchIndex);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


