// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*UTextExtract)(struct UText* ut,long nativeStart,long nativeLimit,unsigned short* dest,int destCapacity,enum UErrorCode* status);
 * }
 */
public interface UTextExtract {

    int apply(java.lang.foreign.MemorySegment ut, long nativeStart, long nativeLimit, java.lang.foreign.MemorySegment replacementText, int replacmentLength, java.lang.foreign.MemorySegment status);
    static MemorySegment allocate(UTextExtract fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$24.const$2, fi, constants$21.const$5, scope);
    }
    static UTextExtract ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _ut, long _nativeStart, long _nativeLimit, java.lang.foreign.MemorySegment _replacementText, int _replacmentLength, java.lang.foreign.MemorySegment _status) -> {
            try {
                return (int)constants$24.const$3.invokeExact(symbol, _ut, _nativeStart, _nativeLimit, _replacementText, _replacmentLength, _status);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


