// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * int (*UTextReplace)(struct UText* ut,long nativeStart,long nativeLimit,unsigned short* replacementText,int replacmentLength,enum UErrorCode* status);
 * }
 */
public interface UTextReplace {

    int apply(java.lang.foreign.MemorySegment ut, long nativeStart, long nativeLimit, java.lang.foreign.MemorySegment replacementText, int replacmentLength, java.lang.foreign.MemorySegment status);
    static MemorySegment allocate(UTextReplace fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$24.const$4, fi, constants$21.const$5, scope);
    }
    static UTextReplace ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _ut, long _nativeStart, long _nativeLimit, java.lang.foreign.MemorySegment _replacementText, int _replacmentLength, java.lang.foreign.MemorySegment _status) -> {
            try {
                return (int)constants$24.const$3.invokeExact(symbol, _ut, _nativeStart, _nativeLimit, _replacementText, _replacmentLength, _status);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


