// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*UTextMapNativeIndexToUTF16)(struct UText* ut,long nativeIndex);
 * }
 */
public interface UTextMapNativeIndexToUTF16 {

    int apply(java.lang.foreign.MemorySegment ut, long nativeIndex);
    static MemorySegment allocate(UTextMapNativeIndexToUTF16 fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$25.const$2, fi, constants$19.const$4, scope);
    }
    static UTextMapNativeIndexToUTF16 ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _ut, long _nativeIndex) -> {
            try {
                return (int)constants$25.const$3.invokeExact(symbol, _ut, _nativeIndex);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


