// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * long (*UTextMapOffsetToNative)(struct UText* ut);
 * }
 */
public interface UTextMapOffsetToNative {

    long apply(java.lang.foreign.MemorySegment ut);
    static MemorySegment allocate(UTextMapOffsetToNative fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$25.const$1, fi, constants$19.const$0, scope);
    }
    static UTextMapOffsetToNative ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _ut) -> {
            try {
                return (long)constants$23.const$4.invokeExact(symbol, _ut);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


