// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct UTextFuncs {
 *     int32_t tableSize;
 *     int32_t reserved1;
 *     int32_t reserved2;
 *     int32_t reserved3;
 *     UTextClone* clone;
 *     UTextNativeLength* nativeLength;
 *     UTextAccess* access;
 *     UTextExtract* extract;
 *     UTextReplace* replace;
 *     UTextCopy* copy;
 *     UTextMapOffsetToNative* mapOffsetToNative;
 *     UTextMapNativeIndexToUTF16* mapNativeIndexToUTF16;
 *     UTextClose* close;
 *     UTextClose* spare1;
 *     UTextClose* spare2;
 *     UTextClose* spare3;
 * };
 * }
 */
public class UTextFuncs {

    public static MemoryLayout $LAYOUT() {
        return constants$26.const$0;
    }
    public static VarHandle tableSize$VH() {
        return constants$26.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t tableSize;
     * }
     */
    public static int tableSize$get(MemorySegment seg) {
        return (int)constants$26.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t tableSize;
     * }
     */
    public static void tableSize$set(MemorySegment seg, int x) {
        constants$26.const$1.set(seg, x);
    }
    public static int tableSize$get(MemorySegment seg, long index) {
        return (int)constants$26.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void tableSize$set(MemorySegment seg, long index, int x) {
        constants$26.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle reserved1$VH() {
        return constants$26.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t reserved1;
     * }
     */
    public static int reserved1$get(MemorySegment seg) {
        return (int)constants$26.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t reserved1;
     * }
     */
    public static void reserved1$set(MemorySegment seg, int x) {
        constants$26.const$2.set(seg, x);
    }
    public static int reserved1$get(MemorySegment seg, long index) {
        return (int)constants$26.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void reserved1$set(MemorySegment seg, long index, int x) {
        constants$26.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle reserved2$VH() {
        return constants$26.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t reserved2;
     * }
     */
    public static int reserved2$get(MemorySegment seg) {
        return (int)constants$26.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t reserved2;
     * }
     */
    public static void reserved2$set(MemorySegment seg, int x) {
        constants$26.const$3.set(seg, x);
    }
    public static int reserved2$get(MemorySegment seg, long index) {
        return (int)constants$26.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void reserved2$set(MemorySegment seg, long index, int x) {
        constants$26.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle reserved3$VH() {
        return constants$26.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int32_t reserved3;
     * }
     */
    public static int reserved3$get(MemorySegment seg) {
        return (int)constants$26.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int32_t reserved3;
     * }
     */
    public static void reserved3$set(MemorySegment seg, int x) {
        constants$26.const$4.set(seg, x);
    }
    public static int reserved3$get(MemorySegment seg, long index) {
        return (int)constants$26.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void reserved3$set(MemorySegment seg, long index, int x) {
        constants$26.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle clone$VH() {
        return constants$26.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * UTextClone* clone;
     * }
     */
    public static MemorySegment clone$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$26.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * UTextClone* clone;
     * }
     */
    public static void clone$set(MemorySegment seg, MemorySegment x) {
        constants$26.const$5.set(seg, x);
    }
    public static MemorySegment clone$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$26.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void clone$set(MemorySegment seg, long index, MemorySegment x) {
        constants$26.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle nativeLength$VH() {
        return constants$27.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * UTextNativeLength* nativeLength;
     * }
     */
    public static MemorySegment nativeLength$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$27.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * UTextNativeLength* nativeLength;
     * }
     */
    public static void nativeLength$set(MemorySegment seg, MemorySegment x) {
        constants$27.const$0.set(seg, x);
    }
    public static MemorySegment nativeLength$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$27.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void nativeLength$set(MemorySegment seg, long index, MemorySegment x) {
        constants$27.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle access$VH() {
        return constants$27.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * UTextAccess* access;
     * }
     */
    public static MemorySegment access$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$27.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * UTextAccess* access;
     * }
     */
    public static void access$set(MemorySegment seg, MemorySegment x) {
        constants$27.const$1.set(seg, x);
    }
    public static MemorySegment access$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$27.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void access$set(MemorySegment seg, long index, MemorySegment x) {
        constants$27.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle extract$VH() {
        return constants$27.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * UTextExtract* extract;
     * }
     */
    public static MemorySegment extract$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$27.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * UTextExtract* extract;
     * }
     */
    public static void extract$set(MemorySegment seg, MemorySegment x) {
        constants$27.const$2.set(seg, x);
    }
    public static MemorySegment extract$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$27.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void extract$set(MemorySegment seg, long index, MemorySegment x) {
        constants$27.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle replace$VH() {
        return constants$27.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * UTextReplace* replace;
     * }
     */
    public static MemorySegment replace$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$27.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * UTextReplace* replace;
     * }
     */
    public static void replace$set(MemorySegment seg, MemorySegment x) {
        constants$27.const$3.set(seg, x);
    }
    public static MemorySegment replace$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$27.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void replace$set(MemorySegment seg, long index, MemorySegment x) {
        constants$27.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle copy$VH() {
        return constants$27.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * UTextCopy* copy;
     * }
     */
    public static MemorySegment copy$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$27.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * UTextCopy* copy;
     * }
     */
    public static void copy$set(MemorySegment seg, MemorySegment x) {
        constants$27.const$4.set(seg, x);
    }
    public static MemorySegment copy$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$27.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void copy$set(MemorySegment seg, long index, MemorySegment x) {
        constants$27.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle mapOffsetToNative$VH() {
        return constants$27.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * UTextMapOffsetToNative* mapOffsetToNative;
     * }
     */
    public static MemorySegment mapOffsetToNative$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$27.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * UTextMapOffsetToNative* mapOffsetToNative;
     * }
     */
    public static void mapOffsetToNative$set(MemorySegment seg, MemorySegment x) {
        constants$27.const$5.set(seg, x);
    }
    public static MemorySegment mapOffsetToNative$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$27.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void mapOffsetToNative$set(MemorySegment seg, long index, MemorySegment x) {
        constants$27.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle mapNativeIndexToUTF16$VH() {
        return constants$28.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * UTextMapNativeIndexToUTF16* mapNativeIndexToUTF16;
     * }
     */
    public static MemorySegment mapNativeIndexToUTF16$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$28.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * UTextMapNativeIndexToUTF16* mapNativeIndexToUTF16;
     * }
     */
    public static void mapNativeIndexToUTF16$set(MemorySegment seg, MemorySegment x) {
        constants$28.const$0.set(seg, x);
    }
    public static MemorySegment mapNativeIndexToUTF16$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$28.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void mapNativeIndexToUTF16$set(MemorySegment seg, long index, MemorySegment x) {
        constants$28.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle close$VH() {
        return constants$28.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * UTextClose* close;
     * }
     */
    public static MemorySegment close$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$28.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * UTextClose* close;
     * }
     */
    public static void close$set(MemorySegment seg, MemorySegment x) {
        constants$28.const$1.set(seg, x);
    }
    public static MemorySegment close$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$28.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void close$set(MemorySegment seg, long index, MemorySegment x) {
        constants$28.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle spare1$VH() {
        return constants$28.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * UTextClose* spare1;
     * }
     */
    public static MemorySegment spare1$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$28.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * UTextClose* spare1;
     * }
     */
    public static void spare1$set(MemorySegment seg, MemorySegment x) {
        constants$28.const$2.set(seg, x);
    }
    public static MemorySegment spare1$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$28.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void spare1$set(MemorySegment seg, long index, MemorySegment x) {
        constants$28.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle spare2$VH() {
        return constants$28.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * UTextClose* spare2;
     * }
     */
    public static MemorySegment spare2$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$28.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * UTextClose* spare2;
     * }
     */
    public static void spare2$set(MemorySegment seg, MemorySegment x) {
        constants$28.const$3.set(seg, x);
    }
    public static MemorySegment spare2$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$28.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void spare2$set(MemorySegment seg, long index, MemorySegment x) {
        constants$28.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle spare3$VH() {
        return constants$28.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * UTextClose* spare3;
     * }
     */
    public static MemorySegment spare3$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$28.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * UTextClose* spare3;
     * }
     */
    public static void spare3$set(MemorySegment seg, MemorySegment x) {
        constants$28.const$4.set(seg, x);
    }
    public static MemorySegment spare3$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$28.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void spare3$set(MemorySegment seg, long index, MemorySegment x) {
        constants$28.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


