// Generated by jextract

package icu;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*UTextClose)(struct UText* ut);
 * }
 */
public interface UTextClose {

    void apply(java.lang.foreign.MemorySegment ut);
    static MemorySegment allocate(UTextClose fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$25.const$4, fi, constants$1.const$0, scope);
    }
    static UTextClose ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _ut) -> {
            try {
                constants$25.const$5.invokeExact(symbol, _ut);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


